### ISSUE TITLE
"Uncaught TypeError: f.state is not a function" for wordpress 4.7

### ISSUE THREAD

**Issue by rosinghal** [themeum/kirki#1227]
Getting error after updating wordpress to 4.7. I have attached the log file. Please have a look.

### Version used:
2.4.0-beta.1

### Using theme_mods or options?
```php
function theme_customize_controls_init() {
	set_theme_mod( 'icon_logo_title', get_bloginfo( 'name' ) );
	set_theme_mod( 'general_front_page', get_option( 'page_on_front' ) );
	set_theme_mod( 'general_posts_page', get_option( 'page_for_posts' ) );
}
add_action( 'customize_controls_init', 'theme_customize_controls_init' );
```
### Attachment
[localhost-1482500062170.log.zip](https://github.com/aristath/kirki/files/670857/localhost-1482500062170.log.zip)

**Comment by aristath** [comment]
I just added your code in my `functions.php` file and didn't get any errors...

But why would you want to add that code in the first place?
Doesn't make any sense to me

**Comment by rosinghal** [comment]
Solved it temporarily. 

```php
Kirki::add_field( 'themename_kirki', array(
	'type'      => 'repeater',
	'settings'  => 'front_page_widget_module_widget',
	'label'     => __( 'Widget Area', 'themename' ),
	'section'   => 'site_front_page_widget_module',
	'priority'  => 100,
	'transport' => 'postMessage',
	'default'   => array(),
	'fields'    => array(
		'widget_name' => array(
			'type'    => 'text',
			'label'   => __( 'Widget Area Name', 'themename' ),
			'default' => ''
		),
		'widget_num' => array(
			'type'    => 'select',
			'label'   => __( 'Number of Widgets per Row', 'themename' ),
			'default' => '1',
			'choices' => array(
				'1' => '1',
				'2' => '2',
				'3' => '3',
				'4' => '4',
				'5' => '5',
				'6' => '6'
			)
		)
	)
) );
```

It worked on removing the **transport** variable. Was it because of **type** was set as **repeater**?

**Comment by aristath** [comment]
repeater controls are currently not compatible with postMessage.
I'm marking this as a feature request so we can do it in a future release.

**Comment by tivnet** [comment]
@aristath Repeater with `postMessage` was working with older WordPress. Now, it produces the `api.state is not a function` error in `customize-controls.js:56`.

**Comment by aristath** [comment]
Currently the repeater control does not support `postMessage` due to some changes in WP Core.
I'm still trying to figure out a solution to this, but until then I'm pushing a commit that will force repeaters to use `refresh`. You can still use `postMessage` in your code if you want, and when we manage to fix this the restriction will be lifted internally.

**Comment by aristath** [comment]
Closing as duplicate of #1208
